In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]

In [3]:
np.arange(my_list)

TypeError: unsupported operand type(s) for -: 'list' and 'int'

In [5]:
my_list

[1, 2, 3]

In [6]:
np.array(my_list)

array([1, 2, 3])

In [8]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [10]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
zeros = np.zeros(4)

In [13]:
zeros

array([0., 0., 0., 0.])

In [14]:
type(my_list)

list

In [15]:
type(my_matrix)

list

In [16]:
type(zeros)

numpy.ndarray

In [17]:
zeros = np.zeros(2,4)

TypeError: data type not understood

In [18]:
zeros = np.zeros((2,4))

In [19]:
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
ones = np.ones(4)

In [21]:
ones

array([1., 1., 1., 1.])

In [22]:
ones = np.ones((2,4))

In [23]:
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [26]:
np.array([1,2,3])

array([1, 2, 3])

In [27]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [28]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
np.random.rand(2)

array([0.55107447, 0.71261167])

In [30]:
np.random.randint(2)

1

In [31]:
np.random.randint(10)

4

In [33]:
np.random.randint(100)

95

In [34]:
np.random.randint(100)

12

In [35]:
np.random.randint(0,199)

100

In [36]:
np.random.rand(1)

array([0.9267382])

In [37]:
np.random.rand(3)

array([0.08884383, 0.95443189, 0.01839484])

In [39]:
np.random.rand(5,5)

array([[0.96238467, 0.13782451, 0.24019018, 0.85917264, 0.16485493],
       [0.80373024, 0.93623458, 0.98429054, 0.64791886, 0.01740274],
       [0.68987788, 0.69322858, 0.17076049, 0.9806142 , 0.42421828],
       [0.39550599, 0.40608481, 0.40192125, 0.04836568, 0.90519882],
       [0.77343899, 0.44880109, 0.64854715, 0.25150913, 0.37747242]])

In [40]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
np.arange(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [42]:
np.random.randint(0,50,10)

array([25, 18, 22, 18, 45, 47, 30, 19, 18, 38])

In [43]:
arr = np.arange(25)

In [44]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [45]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [46]:
arr.reshape()

TypeError: reshape() takes exactly 1 argument (0 given)

In [47]:
arr.reshape(1)

ValueError: cannot reshape array of size 25 into shape (1,)

In [48]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [49]:
arr.shape

(25,)

In [50]:
new_arr = arr.reshape(5,5)

In [51]:
new_arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [52]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [53]:
new_arr.shape

(5, 5)

In [54]:
arr.shape

(25,)

In [55]:
arr.dtype

dtype('int64')

In [56]:
np.arange(0,10).shape

(10,)

In [57]:
np.arange(50)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [58]:
np.arange(3，50)

SyntaxError: invalid character in identifier (<ipython-input-58-0047baf4d31c>, line 1)

In [59]:
np.arange(3,50)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [60]:
np.arange(50).shape

(50,)

In [61]:
np.arange(50).reshape(5,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [62]:
arr2d = np.arange(50).reshape(5,10)

In [63]:
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [64]:
arr2d[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
arr2d[0,2]

2

In [66]:
arr2d[2:4,3:6]

array([[23, 24, 25],
       [33, 34, 35]])

In [67]:
arr = np.arange(11)

In [68]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [69]:
arr[0:3] = 100

In [70]:
arr

array([100, 100, 100,   3,   4,   5,   6,   7,   8,   9,  10])

In [71]:
barr = arr[5:8]

In [72]:
barr

array([5, 6, 7])

In [73]:
barr[:] = 99

In [74]:
barr

array([99, 99, 99])

In [75]:
arr

array([100, 100, 100,   3,   4,  99,  99,  99,   8,   9,  10])

In [76]:
arr = np.arange(50).reshape(5,10)

In [77]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [78]:
arr[[2,4]]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [79]:
arr[[2,4],[4,7]]

array([24, 47])

In [80]:
arr[(2,4),(4,7)]

array([24, 47])

In [81]:
arr[[2,4]]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [82]:
arr[2:4]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [83]:
arr[[2,4]]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [84]:
arr[[2,4],4:7]

array([[24, 25, 26],
       [44, 45, 46]])

In [85]:
numpy

NameError: name 'numpy' is not defined

In [86]:
np

<module 'numpy' from '/Users/fouyang/anaconda3/lib/python3.6/site-packages/numpy/__init__.py'>

In [87]:
import pandas as pd

In [88]:
pd

<module 'pandas' from '/Users/fouyang/anaconda3/lib/python3.6/site-packages/pandas/__init__.py'>

In [89]:
labels = ['a','b','c']
my_list = [10,20,30]
arr = np.array([10,20,30])
d = {'a':10, 'b':20, 'c':30}

In [90]:
labels

['a', 'b', 'c']

In [91]:
my_list

[10, 20, 30]

In [93]:
arr

array([10, 20, 30])

In [94]:
d

{'a': 10, 'b': 20, 'c': 30}

In [95]:
arr.dtype

dtype('int64')

In [96]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [97]:
pd.Series(my_list, labels)

a    10
b    20
c    30
dtype: int64

In [98]:
mys = pd.Series(my_list, labels)

In [99]:
mys

a    10
b    20
c    30
dtype: int64

In [100]:
mys['a']

10

In [101]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [102]:
d

{'a': 10, 'b': 20, 'c': 30}

In [103]:
ser1 = pd.Series([1,2,3,4], index=['USA','GERMANY','USSR','JAPAN'])

In [104]:
ser1

USA        1
GERMANY    2
USSR       3
JAPAN      4
dtype: int64

In [105]:
ser1['USA']

1

In [107]:
from numpy.random import randn
np.random.seed(101)

In [108]:
df = pd.DataFrame(randn(5,4),index='A B C D E'.split(),columns='W X Y Z'.split())

In [109]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [110]:
df = pd.DataFrame(randn(5,4))

In [111]:
df

0         1         2         3
0  0.302665  1.693723 -1.706086 -1.159119
1 -0.134841  0.390528  0.166905  0.184502
2  0.807706  0.072960  0.638787  0.329646
3 -0.497104 -0.754070 -0.943406  0.484752
4 -0.116773  1.901755  0.238127  1.996652